### ISSUE TITLE
Custom options 

### ISSUE THREAD

**Issue by bevack** [natekspencer/BwaSpaManager#1]
Hi, I am completely new to all this so apologies in advanced if this isn’t the right place for this question. 

I have installed this to my SmartThings and it shows up in my app however I can’t seem to see/change the custom options to suit my spa? I can see in the device handlers code there are many features that just don’t show in my app? Please help as this is something I have been looking for to interstate my spa in to my home automation 

![3353D3C3-65C3-47D3-9A56-A5AA998FCA87](https://user-images.githubusercontent.com/76258757/102710626-7aae0d80-42ab-11eb-831f-0f17e1cb0967.jpeg)

**Comment by natekspencer** [comment]
> Hi, I am completely new to all this so apologies in advanced if this isn’t the right place for this question.
> 
> I have installed this to my SmartThings and it shows up in my app however I can’t seem to see/change the custom options to suit my spa? I can see in the device handlers code there are many features that just don’t show in my app? Please help as this is something I have been looking for to interstate my spa in to my home automation
> 
> ![3353D3C3-65C3-47D3-9A56-A5AA998FCA87](https://user-images.githubusercontent.com/76258757/102710626-7aae0d80-42ab-11eb-831f-0f17e1cb0967.jpeg)

Hey @bevack,

Unfortunately this SmartApp was built for the classic app and has not been updated to the SmartThings Connect app, which is why you won't see a number of those other options/configurations available. From what I recall, basic functionality still works like changing heat and toggling on/off pump 1, but that's where it ends.

It's also worth noting that I don't have any current plans of updating this for compatibility with the new app. After a couple of internet outages at home and realizing that SmartThings still fully relies on cloud support to even open the app so I can control my local z-wave devices, I decided to invest in a home automation solution that could still function as long as my home network remained online and also allowed me more flexibility in control of devices and automations both locally and remote.
